missing backslash in if conditional around "only_one_last"
I got this error after installing ibus-table from the git repo:

Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/main.py", line 31, in <module>
    import factory
  File "/usr/share/ibus-table/engine/factory.py", line 27, in <module>
    import table
  File "/usr/share/ibus-table/engine/table.py", line 577
    or only_one_last
                   ^
SyntaxError: invalid syntax